kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:anyuid'
  annotations:
    helm.sh/hook: pre-install
subjects:
  - kind: ServiceAccount
    name: gitlab-shared-secrets
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: gitlab-prometheus-server
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: gitlab-gitlab-runner
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: gitlab-certmanager-issuer
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'