apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: letsencrypt-cert-manager-dns
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - 'route53:ChangeResourceRecordSets'
      - 'route53:GetChange'
      - 'route53:ListHostedZonesByName'
      - 'route53:ListHostedZones'
      effect: Allow
      resource: '*'
  secretRef:
    name: cert-manager-dns-credentials
    namespace: {{ .Release.Namespace }}
---    
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    email: {{ .Values.letsencrypt.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:  
    # ACME DNS-01 provider configurations
    - dns01:
      # Here we define a list of DNS-01 providers that can solve DNS challenges
        route53:
          accessKeyID: dummy
          secretAccessKeySecretRef:
            name: cert-manager-dns-credentials
            key: aws_secret_access_key
          region: dummy
          hostedZoneID: dummy
---          
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: letsencrypt-issuer
  namespace: openshift-gitops
spec:
  serviceAccountRef:
    name: openshift-gitops-argocd-application-controller
  patch:
    targetObjectRef:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-issuer
    patchTemplate: |
      spec:
        acme:
          solvers:
          - dns01:
              route53:
                accessKeyID: {{ "{{" }} (index . 1).data.aws_access_key_id | b64dec {{ "}}" }}
                region: {{ "{{" }} (index . 2).status.platformStatus.aws.region {{ "}}" }}
                hostedZoneID: {{ "{{" }} (index . 3).spec.publicZone.id {{ "}}" }}
                secretAccessKeySecretRef:
                  name: cert-manager-dns-credentials
                  key: aws_secret_access_key
    patchType: application/merge-patch+json
    sourceObjectRefs:
    - apiVersion: v1
      kind: Secret
      namespace: {{ .Release.Namespace }}
      name: cert-manager-dns-credentials
    - apiVersion: config.openshift.io/v1
      kind: Infrastructure
      name: cluster
    - apiVersion: config.openshift.io/v1
      kind: DNS
      name: cluster           
