apiVersion: v1
kind: Secret
metadata:
  name: vault-quay-plugin-creds
type: kubernetes.io/basic-auth
stringData:
  username: "${vault_quay_app_username}"
  quay_org: ${quay_organization}
  password: ${vault_quay_app_token}