apiVersion: v1
kind: Secret
metadata:
  name: vault-github-plugin-creds
type: kubernetes.io/ssh-auth
stringData:
  github_app_id: "${vault_github_app_id}"
  github_org: ${github_organization}
  ssh-privatekey: |
${vault_github_app_private_key}