apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  labels:
    {{- include "aws-provisioner.labels" . | nindent 4 }}  
spec:
  package: "crossplane/provider-aws:v0.29.0"
  controllerConfigRef:
      name: vault-config  