# apiVersion: redhatcop.redhat.io/v1alpha1
# kind: NamespaceConfig
# metadata:
#   name: ghcr-pusher-secret
# spec:
#   labelSelector:
#     matchExpressions:
#       - key: app
#         operator: Exists
#     matchLabels:
#       environment: build      
#   templates:     
#     - objectTemplate: |
#         kind: Secret
#         apiVersion: v1
#         metadata:
#           name: ghcr-pusher
#           namespace: "{{ .Name }}"
#         type: kubernetes.io/dockerconfigjson  
#         data:
#           {{ (lookup "v1" "Secret" "openshift-config" "ghcr-pusher").data | toYaml | indent 2 }}