apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: ghcr-puller-secret
spec:
  labelSelector:
    matchExpressions:
      - key: app
        operator: Exists
  templates:     
    - objectTemplate: |
        kind: Secret
        apiVersion: v1
        metadata:
          name: ghcr-puller
          namespace: "{{ .Name }}"
        type: kubernetes.io/dockerconfigjson  
        data:
          {{ (lookup "v1" "Secret" "openshift-config" "ghcr-puller").data | toYaml | indent 2 }}