apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: github-action-runner-deployment
spec:
  labelSelector:
    matchLabels:
      environment: build
  templates:  
    - objectTemplate: |
        apiVersion: actions.summerwind.dev/v1alpha1
        kind: RunnerDeployment
        metadata:
          name: "{{ .Labels.app }}-buildah-runner"
          namespace: "{{ .Name }}"
        spec:
          replicas: 1
          selector: null
          template:
            metadata: {}
            spec:
              dockerEnabled: false
              dockerdContainerResources: {}
              ephemeral: true
              image: quay.io/redhat-github-actions/buildah-runner:v1.3
              labels:
                - "{{ .Labels.app }}"
                - self-hosted
                - buildah
              organization: {{ (lookup "v1" "Secret" "backstage" "github-credentials").data.GITHUB_ORG | b64dec }}
              resources: 
                requests: 
                  cpu: "200m"
                  memory: "1Gi"
      excludedPaths:
        - .spec.template.metadata
        - .spec.template.spec.image
        - .spec.template.spec.resources
        - .spec.template.spec.dockerdContainerResources
        - .spec.selector
        - .status	
        - .spec.replicas	
        - .metadata
    - objectTemplate: |
        apiVersion: actions.summerwind.dev/v1alpha1
        kind: RunnerDeployment
        metadata:
          name: "{{ .Labels.app }}-java-runner"
          namespace: "{{ .Name }}"
        spec:
          replicas: 1
          selector: null
          template:
            metadata: {}
            spec:
              dockerEnabled: false
              dockerdContainerResources: {}
              ephemeral: true
              image: quay.io/redhat-github-actions/java-runner-11:v1.3
              labels:
                - "{{ .Labels.app }}"
                - self-hosted
                - java
              organization: {{ (lookup "v1" "Secret" "backstage" "github-credentials").data.GITHUB_ORG | b64dec }}
              resources: 
                requests: 
                  cpu: "200m"
                  memory: "1Gi"
      excludedPaths:
        - .spec.template.metadata
        - .spec.template.spec.image
        - .spec.template.spec.resources
        - .spec.template.spec.dockerdContainerResources
        - .spec.selector
        - .status	
        - .spec.replicas	
        - .metadata        