apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: github-action-runner-deployment
spec:
  labelSelector:
    matchLabels:
      environment: build
  templates:  
    - objectTemplate: | 
        apiVersion: actions.summerwind.dev/v1alpha1
        kind: RunnerDeployment
        metadata:
          name: {{ index .Metadata.Annotations "app" }}-build-runner
          namespace: {{ .Name }}
        spec:
          replicas: 2
          spec:
            ephemeral: true
            organization: raf-backstage-demo
            labels: 
              app: {{ index .Metadata.Annotations "app" }}
              runs-on: self-hosted