apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: team-edit-access
spec:
  labelSelector:
    matchExpressions:
      - key: team
        operator: Exists
  templates:     
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: "{{ .Labels.team }}-edit"
          namespace: "{{ .Name }}"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: edit
        subjects:
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: "{{ .Labels.team }}"
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: "{{ .Labels.team }}-build-sa-edit"
          namespace: "{{ .Name }}"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: edit
        subjects:          
        - kind: ServiceAccount
          name: default
          namespace: "{{ index .Labels "build-namespace" }}"