apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: servicemesh-membership
spec:
  labelSelector:
    matchExpressions:
      - key: team
        operator: Exists
      - key: environment
        operator: NotIn
        values:
        - build  
  templates:     
    - objectTemplate: |
        kind: ServiceMeshMember
        apiVersion: maistra.io/v1
        metadata:
          name: default
          namespace: {{ .Name }}
        spec:
          controlPlaneRef:
            name: basic
            namespace: istio-system