apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: team-github-vault-role
spec:
  labelSelector:
    matchExpressions:
      - key: team
        operator: Exists
  templates:     
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: KubernetesAuthEngineRole
        metadata:
          name: {{ .Labels.team }}-vault-role
          namespace: vault-admin
        spec:
          # Add fields here
          authentication: 
            path: kubernetes
            role: policy-admin
          path: kubernetes
          policies:
            - {{ .Labels.team }}-github-read-token
          targetNamespaces:
            targetNamespaceSelector:
              matchLabels:
                team: {{ .Labels.team }}
          targetServiceAccounts:
          - default      
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: Policy
        metadata:
          name: {{ .Labels.team }}-github-read-token
          namespace: vault-admin
        spec:
          # Add fields here
          authentication: 
            path: kubernetes
            role: policy-admin
          policy: |
            # create tokens
            path "/github/token/{{ .Labels.team }}" {
              capabilities = ["read"]
            }
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: GitHubSecretEngineRole
        metadata:
          name: {{ .Labels.team }}
          namespace: vault-admin
        spec:
          authentication: 
            path: kubernetes
            role: policy-admin
          path: github
          # TODO filter down repos
          repositories: []
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: VaultSecret
        metadata:
          name: github-pull-secret
          namespace: {{ .Name }}
        spec:
          vaultSecretDefinitions:
          - authentication:
              path: kubernetes
              role: {{ .Labels.team }}-vault-role
              serviceAccount:
                name: default
            name: githubtoken
            path: github/token/{{ .Labels.team }}
          output:
            name: github-pull-secret
            stringData:
              .dockerconfigjson: |
                {"auths":{"ghcr.io":{"username":"team_puller","password":"{{ "{{" }} .githubtoken.token {{ "}}" }}","email":"team_puller@example.com","auth":"{{ "{{" }} list "team_puller:" .githubtoken.token | join "" | base64 {{ "}}" }}"}}}
            type: kubernetes.io/dockerconfigjson