# Default values for ocp-gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gitlab:
  certmanager:
    installCRDs: false
    install: false
    rbac:
      create: false

  nginx-ingress:
    enabled: false  

  gitlab:
    webservice:
      ingress:
        tls:
          secretName: gitlab-tls

  registry:
    ingress:
      tls:
        secretName: registry-tls

  minio:
    ingress:
      tls:
        secretName: minio-tls

  migrations:
    enabled: false        

global:
  hosts:
    domain: apps.dummy
  ingress:
    enabled: false
    configureCertmanager: false
    tls:
      enabled: true   
      
  migrations:
    enabled: false
