apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dbaas-operator
  labels:
    operators.coreos.com/dbaas-operator.openshift-dbaas-operator: ""  
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: dbaas-operator
  source: dbaas-operator
  sourceNamespace: openshift-marketplace
  startingCSV: dbaas-operator.v0.2.0
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dbaas-operator 
spec:
  targetNamespaces: []