apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: github-group-sync-configuration
spec:
  schedule: "*/30 * * * *"
  providers:
  - name: github
    github:
      credentialsSecret:
        name: github-group-sync
        namespace: group-sync-operator
      organization: dummy
      url: 'https://api.github.com/'
      v4url: 'https://api.github.com/graphql'