apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: github-group-sync-configuration
spec:
  schedule: "*/30 * * * *"
  providers:
  - name: github
    github:
      organization: dummy
      credentialsSecret:
        name: github-group-sync
        namespace: group-sync-operator