kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fairwind-goldilocks-dashboard
spec:
  to:
    kind: Service
    name: "fairwind-goldilocks-dashboard"
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
  wildcardPolicy: None
