apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: puller-secret-service-account-patch
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: default
  patch:
    targetObjectRef:
      apiVersion: v1
      kind: ServiceAccount
      name: default
    sourceObjectRefs:
    - apiVersion: v1
      kind: Namespace
      name: '{{ "{{" }} .metadata.namespace {{ "}}" }}'
    # gives gch-puller to all default service accounts in namespaces with the app label.   
    patchTemplate: |
      imagePullSecrets:
      {{ "{{-" }} if and (hasKey (index . 1).metadata.labels "app") (not (has (dict "name" "ghcr-puller") (index . 0).imagePullSecrets)) {{ "}}" }}      
      {{ "{{" }} append (index . 0).imagePullSecrets (dict "name" "ghcr-puller") | toYaml | indent 2 {{ "}}" }}
      {{ "{{-" }} else {{ "}}" }}
      {{ "{{" }} (index . 0).imagePullSecrets | toYaml | indent 2 {{ "}}" }}
      {{ "{{-" }} end {{ "}}" }}
    patchType: application/merge-patch+json