apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: user-workload-grafana
spec:
  targetNamespaces:
    - user-workload-grafana
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
