apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: pelorus-github-vault-secret
  namespace: pelorus
spec:
  vaultSecretDefinitions:
  - authentication:
      path: kubernetes
      role: pelorus
      serviceAccount:
        name: default
    name: githubtoken
    path: github/token/pelorus
  output:
    name: github-secret
    stringData:
      GIT_TOKEN: "{{ .githubtoken.token }}"
      GIT_USER: pelorus
    type: Opaque