apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: backstag-app-patch
  namespace: openshift-gitops
spec:
  serviceAccountRef:
    name: openshift-gitops-argocd-server
  patch:
    targetObjectRef:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      namespace: openshift-gitops
      name: backstage
    patchTemplate: |
      spec:
        source:
          helm:
            values: |
              base_domain: {{ "{{" }} (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain {{ "}}" }}
    patchType: application/merge-patch+json