{{ if .Values.usePostgresql }}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "backstage.fullname" . }}-postgresql
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
      app.kubernetes.io/instance: backstage
      app.kubernetes.io/name: postgresql
  template:
    metadata:
      name: {{ include "backstage.fullname" . }}-postgresql
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/instance: backstage
        app.kubernetes.io/name: postgresql
    spec:
      containers:
        - name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres  
            - name: POSTGRES_PASSWORD
              value: changeit
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/pgdata/data
          args:
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          ports:
            - name: tcp-postgresql
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgdata
            - name: config
              mountPath: /etc/postgresql   
          terminationMessagePolicy: File
          image: 'docker.io/debezium/postgres:14'
      serviceAccount: default
      volumes:
      - name: config
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: {{ include "backstage.fullname" . }}-postgresql-config
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        volumeMode: Filesystem
  serviceName: {{ include "backstage.fullname" . }}-postgresql
{{ end }}  

