{{ if .Values.usePostgresql }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-postgresql
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: postgresql
{{ end }}    