apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mesh-gateway
  labels:
    {{- include "mesh-ingress.labels" . | nindent 4 }}  
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*/*.mesh.apps.{{ .Values.base_domain }}'
      port:
        name: http
        number: 80
        protocol: HTTP
