apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: database-engine-admin
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  path: kubernetes  
  policies:
    - database-engine-admin
  targetServiceAccounts:
  - default  
  targetNamespaces:
    targetNamespaceSelector:
      matchExpressions:
        - key: team
          operator: Exists
        - key: environment
          operator: NotIn
          values:
          - build