apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: database-engine-admin
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  policy: |
    # query existing mounts
    path "/sys/mounts" {
      capabilities = [ "list", "read"]
      allowed_parameters = {
        "type" = ["database"]
        "*"   = []
      }
    }

    # mount database secrets engines
    # the + is for the db name, assuming the can be more than one db
    path "/sys/mounts/{{identity.entity.aliases.${accessor}.metadata.service_account_namespace}}/+" {
      capabilities = [ "create", "read", "update", "delete"]
      allowed_parameters = {
        "type" = ["database"]
        "*"   = []
      }
    }

    # tune database secrets engines
    path "/sys/mounts/{{identity.entity.aliases.${accessor}.metadata.service_account_namespace}}/+/tune" {
      capabilities = [ "create", "read", "update", "delete"]
    }

    # Configure database secrets engines
    path "/{{identity.entity.aliases.${accessor}.metadata.service_account_namespace}}/+/config/+" {
      capabilities = [ "create", "read", "update", "delete"]
    }

    # Configure database roles
    path "/{{identity.entity.aliases.${accessor}.metadata.service_account_namespace}}/+/roles/+" {
      capabilities = [ "create", "read", "update", "delete"]
    }

    # read secrets
    path "/{{identity.entity.aliases.${accessor}.metadata.service_account_namespace}}/+/creds/+" {
      capabilities = [ "read" ]
    }
    