apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: quay
spec:
  authentication: 
    path: kubernetes
    role: policy-admin
  type: vault-plugin-secrets-quay
  path: ""