apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  labels:
    {{- include "crossplane-system.labels" . | nindent 4 }}   
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Release.Namespace }} 
      name: aws-creds
      key: creds