apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  labels:
    {{- include "crossplane-system.labels" . | nindent 4 }}  
spec:
  package: "crossplane/provider-aws:v1.9.0"