apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: crossplane-creds
  labels:
    {{- include "crossplane-system.labels" . | nindent 4 }}  
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries: 
    - action:
      - "*"
      effect: Allow
      resource: '*'
  secretRef:
    name: aws-creds
    namespace: {{ .Release.Namespace }} 