apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/raffaelespazzoli/backstage-demo.git
    targetRevision: HEAD
    path: cert-manager
    directory:
      include: operator.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 