apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-utils-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/raffaelespazzoli/backstage-demo.git
    targetRevision: HEAD
    path: cert-utils-operator
    directory:
      include: operator.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-utils-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    