apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kcp.fullname" . }}
  labels:
    {{- include "kcp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kcp.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kcp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - start
          - --root-directory
          - ./etcddata
          ports:
            - name: http
              containerPort: 6443
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: readyz
          #     port: http
          #     scheme: HTTPS
          # readinessProbe:
          #   httpGet:
          #     path: readyz
          #     port: http
          #     scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /etcddata            
        - name: admin-secret
          image: registry.redhat.io/openshift4/ose-cli:v4.9
          command: 
          - /bin/bash
          - -c
          - | 
              while true; do
                sleep 5
                if [[ -f /etcddata/admin.kubeconfig ]]; then
                  oc -s https://kubernetes.default.svc:443 --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token --insecure-skip-tls-verify delete secret kcp-init -n kcp
                  oc -s https://kubernetes.default.svc:443 --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token --insecure-skip-tls-verify create secret generic kcp-init -n kcp --from-file=kubeconfig=/etcddata/admin.kubeconfig
                else
                  sleep 5
                fi    
              done
          volumeMounts:
            - name: data
              mountPath: /etcddata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "kcp.fullname" . }}-data                         
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
