apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd
spec:
  # Secret names are always required.
  secretName: etcd-tls
  commonName: etcd-0
  usages:
    - server auth
    - client auth  
  dnsNames:
    - etcd-0.etcd-kcp-headless.{{ .Release.Namespace }}.svc
    - etcd-0.etcd-kcp-headless.{{ .Release.Namespace }}.svc.cluster.local
    - etcd-kcp.{{ .Release.Namespace }}.svc
    - etcd-kcp.{{ .Release.Namespace }}.cluster.local    
  duration: 8760h
  renewBefore: 1h
  issuerRef:
    name: local-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io