kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "kcp.fullname" . }}-data
  labels:
    {{- include "kcp.labels" . | nindent 4 }}  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi