apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcp.fullname" . }}
  labels:
    {{- include "kcp.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: kcp-tls  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kcp.selectorLabels" . | nindent 4 }}
