apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: openshift-config-argocd-app-patch
  namespace: openshift-gitops
spec:
  serviceAccountRef:
    name: openshift-gitops-argocd-server
  patches:
  - targetObjectRef:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      namespace: openshift-gitops
      name: openshift-config
    patchTemplate: |
      spec:
        source:
          helm:
            values: |
              base_domain: {{ "{{" }} (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain {{ "}}" }}
    patchType: application/merge-patch+json
    id: base-domain-patch