apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lets-encrypt-certs
  namespace: openshift-ingress
spec:
  secretName: lets-encrypt-certs-tls
  duration: 168h0m0s
  renewBefore: 1h0m0s
  commonName: '*.apps.{{ .Values.base_domain }}'
  usages:
    - server auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - '*.apps.{{ .Values.base_domain }}'
  issuerRef:
    name: letsencrypt-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: letsencrypt-certs
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: default
  patch:
    targetObjectRef:
      apiVersion: v1
      kind: Secret
      name: lets-encrypt-certs-tls
      namespace: openshift-ingress
    patchTemplate: |
      data:
        cert: {{ "{{" }} (index (index . 1).data "tls.crt") {{ "}}" }}
        key: {{ "{{" }} (index (index . 1).data "tls.key") {{ "}}" }}
    patchType: application/merge-patch+json
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: letsencrypt-ingress-operator
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: default
  patch:
    targetObjectRef:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
    patchTemplate: |
      spec:
        defaultCertificate:
          name: lets-encrypt-certs-tls
    patchType: application/merge-patch+json    
