apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: github-ocp-oauth-provider
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: default
  patch:
    targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      name: cluster
    patchTemplate: |
      spec:
        identityProviders:
        - name: my_htpasswd_provider 
          mappingMethod: claim 
          type: HTPasswd
          htpasswd:
            fileData:
              name: htpass-secret
        - name: backstage-demo-github 
          mappingMethod: claim 
          type: GitHub
          github:
            clientID: {{ "{{" }} (index . 1).data.client_id | b64dec {{ "}}" }} 
            clientSecret: 
              name: ocp-github-app-credentials
            organizations: 
            - raf-backstage-demo
            teams: []            
    patchType: application/merge-patch+json
    sourceObjectRefs:
    - apiVersion: v1
      kind: Secret
      name: ocp-github-app-credentials
      namespace: openshift-config