apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: puller-secret-service-account-patch
  namespace: openshift-gitops
spec:
  serviceAccountRef:
    name: openshift-gitops-argocd-server
  patch:
    targetObjectRef:
      apiVersion: v1
      kind: ServiceAccount
      name: default
    sourceObjectRefs:
    - apiVersion: v1
      kind: Namespace
      name: {{ "{{-" }} .metadata.namespace {{ "{{-" }}
    # gives gch-puller to all default service accounts in namespaces with the app label.   
    patchTemplate: |
      {{ "{{-" }} if (hasKey (index . 1).metadata.labels "app") and not (has (index . 0).imagePullSecrets "ghcr-puller") {{ "}}" }}
      imagePullSecrets:
      {{ "{{-" }} append (index . 0).imagePullSecrets "ghcr-puller" | toYaml | indent 2 {{ "}}" }}
      {{ "{{-" }} end {{ "}}" }}
    patchType: application/merge-patch+json