apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: backstage-postgresql-debezium-connector
  labels:
    strimzi.io/cluster: cdc-kafka
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: "postgresql.backstage.svc"
    database.port: "5432"
    database.user: "postgres"
    database.password: "postgres!"
    #database.dbname: "InternationalDB"
    #database.server.name: "mssql-server-linux"
    table.whitelist: "dbo.Orders"
    database.history.kafka.bootstrap.servers: "cdc-kafka-kafka-bootstrap:9092"
    database.history.kafka.topic: "backstage.entities"  