apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cdc-kafka
  labels:
    {{- include "backstage-kcp-cdc.labels" . | nindent 4 }}  
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '3.0'
      inter.broker.protocol.version: '3.0'
    storage:
      type: persistent-claim
      deleteClaim: true
      size: 10Gi
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    version: 3.0.0
    replicas: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: persistent-claim
      deleteClaim: true
      size: 5Gi
    replicas: 3