apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: cdc-debezium
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels:
    {{- include "backstage-kcp-cdc.labels" . | nindent 4 }}    
spec:
  version: 3.0.0
  replicas: 1
  bootstrapServers: cdc-kafka-kafka-bootstrap.kcp.svc:9092
  build:
    output:
      type: docker
      image: "image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/kafka-connect-build:latest"
    plugins:
      - name: debezium-connector-postgres
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.8.0.Final/debezium-connector-postgres-1.8.0.Final-plugin.tar.gz
            #sha512sum: 82542ed190ec0b7245d0e6554dacec1bb1c65dd3e14e837cdc5898a789482b54af9736d719a9ff50731e61dd9b6a0e741c3ba6f71993e38416dde2753d74f460
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status