apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: cdc-debezium
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels:
    {{- include "backstage-kcp-cdc.labels" . | nindent 4 }}    
spec:
  version: 3.0.0
  replicas: 1
  bootstrapServers: cdc-kafka-kafka-bootstrap.kcp.svc:9092
  build:
    output:
      type: docker
      image: "image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/kafka-connect-build:latest"
    plugins:
      # - name: debezium-connector-postgres
      #   artifacts:
      #     - type: tgz
      #       url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.8.0.Final/debezium-connector-postgres-1.8.0.Final-plugin.tar.gz
      #       #sha512sum: 82542ed190ec0b7245d0e6554dacec1bb1c65dd3e14e837cdc5898a789482b54af9736d719a9ff50731e61dd9b6a0e741c3ba6f71993e38416dde2753d74f460
      #     # - type: zip
      #     #   url: https://maven.repository.redhat.com/ga/io/debezium/debezium-scripting/1.7.2.Final-redhat-00003/debezium-scripting-1.7.2.Final-redhat-00003.zip
      - name: debezium-connector-postgres
        artifacts:
        - type: zip 
          url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-postgres/1.7.2.Final-redhat-00003/debezium-connector-postgres-1.7.2.Final-redhat-00003-plugin.zip  
        - type: zip
          url: https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-distro-connect-converter/2.0.2.Final-redhat-00001/apicurio-registry-distro-connect-converter-2.0.2.Final-redhat-00001.zip
        - type: zip
          url: https://maven.repository.redhat.com/ga/io/debezium/debezium-scripting/1.7.2.Final-redhat-00003/debezium-scripting-1.7.2.Final-redhat-00003.zip            
  config:
    group.id: backstage-kcp-cdc-connect-cluster
    offset.storage.topic: backstage-kcp-cdc-connect-cluster-offsets
    config.storage.topic: backstage-kcp-cdc-connect-cluster-configs
    status.storage.topic: backstage-kcp-cdc-connect-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3    