apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pusher-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-pusher
subjects:          
- kind: ServiceAccount
  name: builder
  namespace: "{{ .Release.Namespace }}"