apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pusher-builder
  labels:
    {{- include "backstage-kcp-cdc.labels" . | nindent 4 }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-pusher
subjects:          
- kind: ServiceAccount
  name: builder
  namespace: "{{ .Release.Namespace }}"