---
apiVersion: v1
kind: Namespace
metadata:
  name: app-3-build
  labels:
    app : app-3
    team: demo-team-b
    build-namespace: app-3-build
    size: medium
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-3-dev
  labels:
    app : app-3
    team: demo-team-b
    build-namespace: app-3-build
    size: medium
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-3-qa
  labels:
    app : app-3
    team: demo-team-b
    build-namespace: app-3-build
    size: medium
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-3-prod
  labels:
    app : app-3
    team: demo-team-b
    build-namespace: app-3-build
    size: medium
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"