---
apiVersion: v1
kind: Namespace
metadata:
  name: app-4-build
  labels:
    app : app-4
    team: demo-team-b
    build-namespace: app-4-build
    size: medium
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-4-dev
  labels:
    app : app-4
    team: demo-team-b
    build-namespace: app-4-build
    size: medium
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-4-qa
  labels:
    app : app-4
    team: demo-team-b
    build-namespace: app-4-build
    size: medium
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-4-prod
  labels:
    app : app-4
    team: demo-team-b
    build-namespace: app-4-build
    size: medium
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"